name: Deploy iicsIngest HML
on:
  push:
    branches: [ main ]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Deploy do iicsIngest em HML
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          set -e  # Sai imediatamente se qualquer comando falhar
                  
          # Diretorios
          BASE_DIR="/opt/engenharia/iicsIngest"
          HML_DIR="$BASE_DIR/hml"
          
          # Ir para a raiz do repositorio
          cd $BASE_DIR

          # Baixa as últimas alterações do remote main e redefine o branch local para corresponder exatamente
          git fetch origin main
          git reset --hard origin/main
          
          # Prepara e limpa o diretório hml
          rm -rf $HML_DIR/*
          mkdir -p $HML_DIR
          cp *.py requirements.txt pyproject.toml $HML_DIR/
          rm *.py requirements.txt pyproject.toml
                                                      
          cd $HML_DIR
          
          # Cria o arquivo .env (use seus segredos reais em vez de valores fixos)       
          cat > .env <<EOF
          ENV=${{ secrets.ENV_HML }}
          MYSQL_HOST=${{ secrets.MYSQL_HOST }}
          MYSQL_PORTA=${{ secrets.MYSQL_PORTA }}
          MYSQL_DATABASE=${{ secrets.MYSQL_DATABASE }}
          MYSQL_USER=${{ secrets.MYSQL_USER }}
          MYSQL_PASSWORD=${{ secrets.MYSQL_PASSWORD }}
          
          SECRET_KEY=${{ secrets.SECRET_KEY }}
          FLASK_DEBUG=${{ secrets.FLASK_DEBUG_HML }}
          FLASK_PORTA=${{ secrets.FLASK_PORTA_HML }}
           
          EOF
          
          # Configura o ambiente virtual
          rm -rf venv
          python3 -m venv venv
          . venv/bin/activate
          pip install --upgrade pip
          pip install -r requirements.txt
          
          echo "=== HML DEPLOY SUCCESS ==="